### ISSUE TITLE
Attribute notQName allowed for the xs:any of an openContent/defaultOpenContent

### ISSUE THREAD

**Issue by brunato** [w3c/xsdtests#1]
Hello,
In the XSD 1.1 tests the particle xs:any inside an *openContent* or *defaultOpenContent* is considered to allow the notQName attribute, so for example the cases `xsdtests/saxonData/Wild/wild074.xsd` and `xsdtests/ibmData/instance_invalid/S3_4_1/s3_4_1ii04.xsd` are signed as valid schemas.

But in the [XSD 1.1 meta-schema](https://www.w3.org/TR/xmlschema11-1/#normative-schemaSchema) the particle xs:any declare for an *openContent/defaultOpenContent* does not allow the attribute notQName.
So which is wrong?

Thank you

**Comment by michaelhkay** [comment]
You appear to be correct that the schema documents used in these tests do not conform to the published S4SD.

I can't see any technical reason for disallowing the notQName attribute on any xs:any wildcard that appears within openContent. One might argue that it serves no useful purpose, but the XSD working group generally avoided "paternalism" - that is, putting an artificial restriction in the spec merely because they didn't think something was useful. So it could be an oversight in the S4SD. We will never know.

Michael Kay

**Comment by brunato** [comment]
Yes, it should be an oversight due to different syntax that notQName has in xs:any and in xs:anyAttribute. In this case, for using the meta-schema in validation may have sense to redefine the openContent to include also the notQName in the <any> particle.

Thanks
